### PR TITLE
feature/get_response

### PR DESCRIPTION
**Pull request by louis-zh**
- `/get_response` with placeholder response for chatGPT response
- modified `/register` to return user_id; used to pass as param for `/store_message` and '/get_response'

Will work on calling chatGPT api

### CODE REVIEW

**Review by xs0203401 — APPROVED** [review]
New Added looks good... 

Just make sure to pull the update from the main first ... and keep the existing code unchanged......

**Comment by xs0203401** [comment]
Let me merge the conflicts as mine was most recently updated ......

**Comment by xs0203401** [comment]
@Criss-Wang @louis-zh 
Please review the changes and approve.

**Review by Criss-Wang — APPROVED** [review]
LGTM

**Pull request merged**
